baseURL: https://www.rowmate.org/
languageCode: de-CH
title: Rowmate
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/rowmate_inv_cut.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Gemeinsam Rudern
    # Hero subtitle (optional)
    subtitle: Rowmate ermöglicht es, sich innerhalb des Vereins zum Rudern zu verabreden.
    # Button text
    buttontext: Jetzt mitgestalten!
    # Where the main hero button links to
    buttonlink: "https://docs.google.com/forms/d/e/1FAIpQLSeSbyM6s1diqJ2BzaypQHqySLfD_CRDxchW4bl-zr6Pje3kMw/viewform?usp=sf_link"
    # Hero image (from static/images/___)
    image: illustrations/rowing_gray.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Kontakt
    url: "#contact"
  # section1:
  #   title: Great power comes
  #   subtitle: with great responsibility
  #   tiles:
  #   - title: App builder
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Free trial
  #   - title: Cloud integration
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: rowmate_inv.png
    # Social Media Title
    socialmediatitle: Folge uns
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/maurosbicego/rowmate
      # Icons are from Font Awesome
      icon: github

    bulmalogo: false
    quicklinks:
      column1:
        title: "Allgemein"
        links:
        - text: Kontakt
          link: "#kontakt"
