baseURL: https://www.rowmate.org/
languageCode: de-CH
title: Rowmate
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/rowmate_inv_cut.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Gemeinsam Rudern
    # Hero subtitle (optional)
    subtitle: Rowmate ermöglicht es, sich innerhalb des Vereins zum Rudern zu verabreden.
    # Button text
    buttontext: Jetzt mitgestalten!
    # Where the main hero button links to
    buttonlink: "https://docs.google.com/forms/d/e/1FAIpQLSeSbyM6s1diqJ2BzaypQHqySLfD_CRDxchW4bl-zr6Pje3kMw/viewform?usp=sf_link"
    # Hero image (from static/images/___)
    image: illustrations/rowing_gray.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Kontakt
    url: "#contact"
  plannedfunctions:
    title: Geplante Funktionen
    tiles:
    - title: Planen von Events
      icon: calendar-alt
      text: Events können eingetragen werden. Nutzer können sich für diese Events anmelden und sich für bestimmte Boote melden (Teams bilden).
    - title: Vermittlung zwichen Mitgliedern
      icon: users
      text: Nutzer können sich untereinander austauschen und sich zum Rudern verabreden
    - title: Marktplatz
      icon: handshake
      text: Nutzer können Anzeigen schalten (suche / biete an). Interessenten können sich schliesslich per Chat beim Verkäufer / Käufer melden

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: rowmate_inv.png
    # Social Media Title
    socialmediatitle: Folge uns
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/maurosbicego/rowmate
      # Icons are from Font Awesome
      icon: github

    bulmalogo: false
    quicklinks:
      column1:
        title: "Allgemein"
        links:
        - text: Kontakt
          link: "#contact"
